<a href="https://colab.research.google.com/github/juancardonaocampo336-wq/Python-1/blob/main/clase_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#\1) Crea una matriz de 3 x 3 con todos los valores true
import numpy as np

Matriz = np.random.randint(low = 1, high=20, size=(3,3))
matriz < 3

print(Matriz)

np.random.choice([True, False], size=(3, 3))


[[10  6 11]
 [ 2 10  7]
 [14  4 18]]


array([[ True, False, False],
       [ True,  True,  True],
       [ True, False,  True]])

In [ ]:
#Reemplace todos los numeros impares por -1

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 != 0] = -1

print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
#Convertir un array de 1D en uno de 2D con dos filas con la misma cantidad de elementos
#Input:

arr = np.arange(16)
new_arr = arr.reshape(2, 8)
print(new_arr)

#ayuda: Investigar el metodo reshape  que tienen los arreglos de numpy

#La función reshape() de NumPy sirve para cambiar la forma (dimensiones) de un arreglo, sin modificar sus datos.

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [ ]:
#Convierte los vectores fila a y b en un vector columna (Apila verticalmente los vectores a y b)
#Input

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

operación = np.vstack((a, b)).reshape(1,-1)

print((a),"\n")
print(b)
print("\n")
print(operación)
#ayuda: investigar las funciones np.vstack , np.hstack



[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[1 1 1 1 1]
 [1 1 1 1 1]]


[[0 1 2 3 4 5 6 7 8 9 1 1 1 1 1 1 1 1 1 1]]


In [ ]:
#Identifica los elementos iguales en a y b
#Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#ayuda: investigar la funcion np.where


# Encontrar los elementos que son iguales
indices = np.where(a == b)

# Mostrar los resultados
print("Índices donde son iguales:", indices)
print("Elementos iguales:", b[indices])


#El resultado son posiciones

Índices donde son iguales: (array([1, 3, 5, 7]),)
Elementos iguales: [2 2 4 4]


In [ ]:
#Intercambiar las columnas 1 y 2 en el array arr
arr = np.arange(9).reshape(3,3)
arr = np.arange(9).reshape(3,3)


# Intercambiar las columnas 1 y 2
arr[:, [0, 1]] = arr[:, [1, 0]]

arr2 = arr[:: , [1,0,2]]

print((arr) ,"\n")
print(arr2)

[[1 0 2]
 [4 3 5]
 [7 6 8]] 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
